CREATE TABLE [dbo].[VID_FELOTES](
	[DYT_ID_TRASPASO_ENC] [numeric](18, 0) NOT NULL,
	[CAB_COD_TP_FACTURA] [char](3) NOT NULL,
	[CAB_FOL_DOCTO_INT] [numeric](18, 0) NOT NULL,
	[DET_NUM_LINEA_DET] [numeric](18, 0) NOT NULL,
	[LOTE] [nvarchar](30) NOT NULL,
	[ITEMCODE] [nvarchar](20) NOT NULL,
	[CANTIDAD] [NUMERIC](18,6) NOT NULL,
	[DUEDATE] [datetime] NULL,
	[VALOR1]  [varchar](250) NULL,
	[VALOR2]  [varchar](250) NULL,
	[VALOR3]  [varchar](250) NULL,
	[VALOR4]  [varchar](250) NULL,
	[VALOR5]  [varchar](250) NULL,
	[VALOR6]  [varchar](250) NULL,
	[VALOR7]  [varchar](250) NULL,
 CONSTRAINT [KVID_FELOTES_PR] PRIMARY KEY CLUSTERED 
(
	[DYT_ID_TRASPASO_ENC] ASC,
	[CAB_COD_TP_FACTURA] ASC,
	[CAB_FOL_DOCTO_INT] ASC,
	[DET_NUM_LINEA_DET] ASC,
	[LOTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

--select * from VID_FELOTES
